"""add webhook delivery retry lock

Revision ID: 174cc4eefdca
Revises: 3907bacd39d1
Create Date: 2026-09-21 12:22:17.238601

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "174cc4eefdca"
down_revision: str | Sequence[str] | None = "3907bacd39d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "webhook_deliveries",
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "webhook_deliveries",
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "webhook_deliveries",
        sa.Column("locked_by", sa.String(length=255), nullable=True),
    )
    op.create_index(
        op.f("ix_webhook_deliveries_locked_until"),
        "webhook_deliveries",
        ["locked_until"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_deliveries_next_attempt_at"),
        "webhook_deliveries",
        ["next_attempt_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_webhook_deliveries_next_attempt_at"), table_name="webhook_deliveries"
    )
    op.drop_index(
        op.f("ix_webhook_deliveries_locked_until"), table_name="webhook_deliveries"
    )
    op.drop_column("webhook_deliveries", "locked_by")
    op.drop_column("webhook_deliveries", "locked_until")
    op.drop_column("webhook_deliveries", "next_attempt_at")
    # ### end Alembic commands ###
