"""create initial tables

Revision ID: 8031c80a68ab
Revises:
Create Date: 2026-08-26 12:30:00.919536

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8031c80a68ab"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_centers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("identifier", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_work_centers_identifier"), "work_centers", ["identifier"], unique=True
    )
    op.create_table(
        "batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("task_description", sa.Text(), nullable=False),
        sa.Column("work_center_id", sa.Integer(), nullable=False),
        sa.Column("shift", sa.String(length=50), nullable=False),
        sa.Column("team", sa.String(length=255), nullable=False),
        sa.Column("batch_number", sa.Integer(), nullable=False),
        sa.Column("batch_date", sa.Date(), nullable=False),
        sa.Column("nomenclature", sa.String(length=255), nullable=False),
        sa.Column("ekn_code", sa.String(length=100), nullable=False),
        sa.Column("shift_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("shift_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["work_center_id"],
            ["work_centers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_number", "batch_date", name="uq_batch_number_date"),
    )
    op.create_index("idx_batch_closed", "batches", ["is_closed"], unique=False)
    op.create_index(
        "idx_batch_shift_times", "batches", ["shift_start", "shift_end"], unique=False
    )
    op.create_index(
        op.f("ix_batches_batch_date"), "batches", ["batch_date"], unique=False
    )
    op.create_index(
        op.f("ix_batches_batch_number"), "batches", ["batch_number"], unique=False
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unique_code", sa.String(length=255), nullable=False),
        sa.Column("batch_id", sa.Integer(), nullable=False),
        sa.Column("is_aggregated", sa.Boolean(), nullable=False),
        sa.Column("aggregated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_product_batch_aggregated",
        "products",
        ["batch_id", "is_aggregated"],
        unique=False,
    )
    op.create_index(
        op.f("ix_products_batch_id"), "products", ["batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_products_is_aggregated"), "products", ["is_aggregated"], unique=False
    )
    op.create_index(
        op.f("ix_products_unique_code"), "products", ["unique_code"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_unique_code"), table_name="products")
    op.drop_index(op.f("ix_products_is_aggregated"), table_name="products")
    op.drop_index(op.f("ix_products_batch_id"), table_name="products")
    op.drop_index("idx_product_batch_aggregated", table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_batches_batch_number"), table_name="batches")
    op.drop_index(op.f("ix_batches_batch_date"), table_name="batches")
    op.drop_index("idx_batch_shift_times", table_name="batches")
    op.drop_index("idx_batch_closed", table_name="batches")
    op.drop_table("batches")
    op.drop_index(op.f("ix_work_centers_identifier"), table_name="work_centers")
    op.drop_table("work_centers")
    # ### end Alembic commands ###
